#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_MAX_TOKENS = 180000;

function usage() {
  console.error("Usage: node scripts/build-context.mjs --source <path> --out src/context.generated.ts [--max-tokens 180000]");
  process.exit(2);
}

function parseArgs(argv) {
  const args = { maxTokens: DEFAULT_MAX_TOKENS };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--source") args.source = argv[++i];
    else if (arg === "--out") args.out = argv[++i];
    else if (arg === "--max-tokens") args.maxTokens = Number(argv[++i]);
    else usage();
  }
  if (!args.source || !args.out || !Number.isFinite(args.maxTokens)) usage();
  return args;
}

function walk(dir, root, out) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const rel = path.relative(root, full).replaceAll(path.sep, "/");
    if (entry.isDirectory()) {
      if (rel === ".lake" || rel === "lake-packages" || rel.startsWith(".lake/") || rel.startsWith("lake-packages/")) {
        continue;
      }
      walk(full, root, out);
    } else if (entry.isFile() && rel.endsWith(".lean")) {
      out.push(rel);
    }
  }
}

function collectFiles(source) {
  const files = [];
  const theory = "Original-Paper/Theory.md";
  if (existsSync(path.join(source, theory))) files.push(theory);

  const leanFiles = [];
  walk(source, source, leanFiles);
  files.push(...leanFiles.sort((a, b) => a.localeCompare(b)));

  for (const rel of ["lakefile.toml", "LICENSE"]) {
    if (existsSync(path.join(source, rel))) files.push(rel);
  }
  return files;
}

const { source, out, maxTokens } = parseArgs(process.argv.slice(2));
const sourcePath = path.resolve(source);
if (!existsSync(sourcePath) || !statSync(sourcePath).isDirectory()) {
  throw new Error(`Source checkout does not exist or is not a directory: ${sourcePath}`);
}

const files = collectFiles(sourcePath);
if (files.length === 0) {
  throw new Error(`No context files found in ${sourcePath}`);
}

const context = files
  .map((rel) => {
    const text = readFileSync(path.join(sourcePath, rel), "utf8").replace(/\r\n/g, "\n");
    return `===== FILE: ${rel} =====\n${text}`;
  })
  .join("\n\n");

const approxTokens = Math.ceil(context.length / 3.5);
if (approxTokens > maxTokens) {
  throw new Error(`Context estimate ${approxTokens} exceeds guard ${maxTokens}`);
}

const commit = execFileSync("git", ["-C", sourcePath, "rev-parse", "--short", "HEAD"], {
  encoding: "utf8"
}).trim();

const outPath = path.resolve(out);
const moduleText = [
  "// Generated by scripts/build-context.mjs. Do not edit by hand.",
  `export const CONTEXT: string = ${JSON.stringify(context)};`,
  `export const SOURCE_COMMIT = ${JSON.stringify(commit)};`,
  `export const CONTEXT_APPROX_TOKENS = ${approxTokens};`,
  ""
].join("\n");

writeFileSync(outPath, moduleText, "utf8");

const relativeOut = path.relative(path.dirname(fileURLToPath(import.meta.url)), outPath).replaceAll(path.sep, "/");
console.log(`WeldAndArrow context written to ${relativeOut}`);
console.log(`SOURCE_COMMIT=${commit}`);
console.log(`CONTEXT_APPROX_TOKENS=${approxTokens}`);
